#!/usr/bin/env python3
"""
ED2E training script — DDP + bf16 AMP + gradient accumulation.

Data layout expected:
    <data-dir>/
        packed_stage3/          ← Stage3PackedDataset (sharded)
        split.json              ← {"train": [...], "val": [...], "test": [...]}
        energy_stats.json       ← {"mean": (6,), "std": (6,), "target_names": [...]}

Generated by scripts/preprocess_edbench.py.

Single-GPU usage
----------------
::

    python scripts/train.py \
        --data-dir  data/ed_energy_5w \
        --csv-path  data/ed_energy_5w/raw/ed_energy_5w.csv \
        --out-dir   runs/stage6_k3 \
        --num-bblocks 3 --batch-size 8 --epochs 100 --device cuda

Multi-GPU (DDP via torchrun)
-----------------------------
::

    torchrun --nproc_per_node=8 scripts/train.py \
        --data-dir  data/ed_energy_5w \
        --csv-path  data/ed_energy_5w/raw/ed_energy_5w.csv \
        --out-dir   runs/stage6_ddp \
        --num-bblocks 3 --batch-size 8 --grad-accum 2 \
        --epochs 100 --num-workers 4

Effective batch size = batch_size × num_gpus × grad_accum.

Resume from checkpoint:
    torchrun ... --resume runs/stage6_ddp/best.pt
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from contextlib import nullcontext
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import DataLoader, Dataset, DistributedSampler

try:
    import wandb as _wandb
    _WANDB_AVAILABLE = True
except ImportError:
    _WANDB_AVAILABLE = False

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(_HERE))

from ed2e.data.energy_stats import load_energy_labels, load_energy_stats, denormalise
from ed2e.data.stage3_local import Stage3Sample, collate_stage3_samples
from ed2e.data.stage3_packed import Stage3PackedDataset
from ed2e.model.bblock import BBlockConfig
from ed2e.model.ed2e import ED2EConfig, ED2EModel, TARGET_NAMES
from ed2e.model.readout import ReadoutConfig


# ══════════════════════════════════════════════════════════════════════════════
# Distributed helpers
# ══════════════════════════════════════════════════════════════════════════════

def _init_distributed() -> Tuple[int, int, int, bool]:
    """
    Detect torchrun environment and initialise NCCL process group.

    Returns
    -------
    rank, world_size, local_rank, is_ddp
    """
    local_rank = int(os.environ.get("LOCAL_RANK", -1))
    if local_rank == -1:
        return 0, 1, 0, False
    dist.init_process_group("nccl")
    rank       = dist.get_rank()
    world_size = dist.get_world_size()
    torch.cuda.set_device(local_rank)
    return rank, world_size, local_rank, True


# ══════════════════════════════════════════════════════════════════════════════
# Dataset wrapper
# ══════════════════════════════════════════════════════════════════════════════

class LabeledPackedDataset(Dataset):
    """
    Wraps Stage3PackedDataset, attaching energy labels from CSV.
    Returns (Stage3Sample, label_normalised) pairs.
    """

    def __init__(
        self,
        packed_dir: str,
        csv_path: str,
        mol_ids: List[str],
        norm_stats: Dict[str, np.ndarray],
    ) -> None:
        self.label_map = load_energy_labels(csv_path)
        mean = norm_stats["mean"]   # (6,)
        std  = norm_stats["std"]    # (6,)

        # Intersect mol_ids with both packed dataset content and CSV labels
        packed_mol_set = set(Stage3PackedDataset(packed_dir).mol_ids)
        self.mol_ids = [m for m in mol_ids if m in self.label_map and m in packed_mol_set]
        if not self.mol_ids:
            raise ValueError(
                f"No labelled molecules found in packed dataset. "
                f"Packed dataset has {len(packed_mol_set)} molecules; "
                f"check csv_path and that preprocessing is complete."
            )

        self.base    = Stage3PackedDataset(packed_dir, mol_ids=self.mol_ids)
        self._mean   = mean
        self._std    = std

    def __len__(self) -> int:
        return len(self.mol_ids)

    def __getitem__(self, idx: int) -> Tuple[Stage3Sample, np.ndarray]:
        sample = self.base[idx]
        mol_id = self.mol_ids[idx]
        raw    = self.label_map[mol_id]           # (6,) float32
        normed = (raw - self._mean) / self._std   # (6,) float32
        return sample, normed


def labeled_collate(batch):
    """
    Returns CPU tensors only.  The training loop moves them to the target
    device with non_blocking=True after the DataLoader yields them, which
    lets DMA transfers overlap with the preceding GPU work.
    """
    samples, labels = zip(*batch)
    tb      = collate_stage3_samples(list(samples))   # CPU Stage3TensorBatch
    targets = torch.tensor(np.stack(labels), dtype=torch.float32)
    return tb, targets


# ══════════════════════════════════════════════════════════════════════════════
# Training helpers
# ══════════════════════════════════════════════════════════════════════════════

@torch.no_grad()
def _evaluate(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
    norm_stats: Dict[str, np.ndarray],
    num_targets: int,
    target_names: Tuple[str, ...],
    amp_ctx,
) -> Dict[str, float]:
    """Compute per-target MAE in Hartree (denormalised)."""
    model.eval()
    mean_t = torch.tensor(norm_stats["mean"], dtype=torch.float32, device=device)
    std_t  = torch.tensor(norm_stats["std"],  dtype=torch.float32, device=device)

    abs_errors: List[torch.Tensor] = []
    total_loss = 0.0
    n_batches  = 0

    for batch, targets in loader:
        batch   = batch.to(device, non_blocking=True)
        targets = targets.to(device, non_blocking=True)

        with amp_ctx:
            out  = model(batch)
            pred = out["energy_pred"].float()   # cast back to fp32 for metrics

        loss = sum(
            F.huber_loss(pred[:, t], targets[:, t], delta=1.0)
            for t in range(num_targets)
        ) / num_targets
        total_loss += float(loss)
        n_batches  += 1

        pred_raw    = pred * std_t + mean_t
        targets_raw = targets * std_t + mean_t
        abs_errors.append((pred_raw - targets_raw).abs().cpu())

    mae_per_target = torch.cat(abs_errors, dim=0).mean(dim=0)   # (T,)
    result = {"loss": total_loss / max(n_batches, 1)}
    for i, name in enumerate(target_names):
        result[f"mae_{name}"] = float(mae_per_target[i])
    result["mae_mean"] = float(mae_per_target.mean())
    return result


def _save_checkpoint(
    path: str,
    model: ED2EModel,
    norm_stats: Dict[str, np.ndarray],
    epoch: int,
    val_mae: np.ndarray,
) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    torch.save(
        {
            "config":     model.cfg,
            "state_dict": model.state_dict(),
            "norm_mean":  norm_stats["mean"],
            "norm_std":   norm_stats["std"],
            "epoch":      epoch,
            "val_mae":    val_mae,
        },
        path,
    )


# ══════════════════════════════════════════════════════════════════════════════
# CLI
# ══════════════════════════════════════════════════════════════════════════════

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Train ED2EModel on EDBench energy prediction.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--data-dir",    required=True,
                   help="Root dir containing packed_stage3/, split.json, energy_stats.json")
    p.add_argument("--csv-path",    required=True,
                   help="Path to ed_energy_5w.csv (for energy labels)")
    p.add_argument("--out-dir",     required=True,
                   help="Checkpoint / log output directory")

    # model
    p.add_argument("--num-bblocks",  type=int,   default=3)
    p.add_argument("--num-heads",    type=int,   default=4)
    p.add_argument("--head-hidden",  type=int,   default=128)
    p.add_argument("--dropout",      type=float, default=0.1)

    # training
    p.add_argument("--batch-size",   type=int,   default=8)
    p.add_argument("--epochs",       type=int,   default=100)
    p.add_argument("--lr",           type=float, default=1e-3)
    p.add_argument("--weight-decay", type=float, default=1e-4)
    p.add_argument("--grad-accum",   type=int,   default=1,
                   help="Gradient accumulation steps. Effective batch = "
                        "batch_size × num_gpus × grad_accum.")
    p.add_argument("--num-workers",  type=int,   default=4,
                   help="DataLoader workers per process")

    # precision / memory
    p.add_argument("--no-amp",  action="store_true",
                   help="Disable bfloat16 AMP (default: AMP enabled on CUDA)")

    # misc
    p.add_argument("--device",   default="cuda" if torch.cuda.is_available() else "cpu")
    p.add_argument("--resume",   default=None,
                   help="Path to checkpoint to resume from")
    p.add_argument("--log-every", type=int, default=50,
                   help="Log training loss every N optimizer steps (rank-0 only)")

    # wandb
    p.add_argument("--wandb",         action="store_true")
    p.add_argument("--wandb-project", default="ed2e")
    p.add_argument("--wandb-entity",  default=None)
    p.add_argument("--wandb-run-name", default=None)
    p.add_argument("--wandb-tags",    nargs="*", default=None)
    return p.parse_args()


# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    args = _parse_args()

    # ── Distributed init ──────────────────────────────────────────────────────
    rank, world_size, local_rank, is_ddp = _init_distributed()
    is_main = (rank == 0)

    # ── Device ───────────────────────────────────────────────────────────────
    if is_ddp:
        device = torch.device(f"cuda:{local_rank}")
    else:
        device = torch.device(args.device)

    # TF32: free matmul speed on Ampere+ (H200 = Hopper, also supported)
    if device.type == "cuda":
        torch.set_float32_matmul_precision("high")
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True

    if is_main:
        os.makedirs(args.out_dir, exist_ok=True)

    # ── AMP context ───────────────────────────────────────────────────────────
    use_amp = not args.no_amp and device.type == "cuda"
    amp_ctx = torch.autocast("cuda", dtype=torch.bfloat16) if use_amp else nullcontext()
    if is_main:
        print(f"AMP: {'bf16' if use_amp else 'disabled'}")

    packed_dir  = os.path.join(args.data_dir, "packed_stage3")
    split_path  = os.path.join(args.data_dir, "split.json")
    stats_path  = os.path.join(args.data_dir, "energy_stats.json")

    # ── Split & stats ─────────────────────────────────────────────────────────
    if is_main:
        print(f"Loading split from {split_path} …")
    with open(split_path) as f:
        splits = json.load(f)
    if is_main:
        print(f"  train={len(splits['train'])}  val={len(splits['val'])}  "
              f"test={len(splits.get('test', []))}")

    if is_main:
        print(f"Loading energy stats from {stats_path} …")
    norm_stats = load_energy_stats(stats_path)

    # ── Datasets ─────────────────────────────────────────────────────────────
    train_ds = LabeledPackedDataset(packed_dir, args.csv_path, splits["train"], norm_stats)

    _val_ids = splits.get("val", [])
    try:
        val_ds: Optional[LabeledPackedDataset] = LabeledPackedDataset(
            packed_dir, args.csv_path, _val_ids, norm_stats
        )
    except ValueError:
        val_ds = None

    if is_main:
        print(f"  train={len(train_ds)}  val={len(val_ds) if val_ds else 0} (labelled)")

    # ── DataLoaders ───────────────────────────────────────────────────────────
    train_sampler = (
        DistributedSampler(train_ds, num_replicas=world_size, rank=rank, shuffle=True)
        if is_ddp else None
    )
    train_loader = DataLoader(
        train_ds,
        batch_size=args.batch_size,
        sampler=train_sampler,
        shuffle=(train_sampler is None),
        collate_fn=labeled_collate,
        num_workers=args.num_workers,
        pin_memory=(device.type == "cuda"),
        persistent_workers=(args.num_workers > 0),
    )

    val_loader: Optional[DataLoader] = None
    if val_ds is not None:
        # Validation runs only on rank 0 to avoid duplicate metric computation.
        # No DistributedSampler needed; we only evaluate on the main process.
        val_loader = DataLoader(
            val_ds,
            batch_size=args.batch_size,
            shuffle=False,
            collate_fn=labeled_collate,
            num_workers=args.num_workers,
            pin_memory=(device.type == "cuda"),
            persistent_workers=(args.num_workers > 0),
        )

    # ── Model ─────────────────────────────────────────────────────────────────
    cfg = ED2EConfig(
        bblock=BBlockConfig(num_bblocks=args.num_bblocks),
        readout=ReadoutConfig(num_heads=args.num_heads),
        energy_head_hidden=args.head_hidden,
        energy_dropout=args.dropout,
    )

    start_epoch  = 0
    best_val_mae = float("inf")

    if args.resume:
        if is_main:
            print(f"Resuming from {args.resume} …")
        ckpt = torch.load(args.resume, map_location="cpu")
        raw_model = ED2EModel(ckpt["config"]).to(device)
        raw_model.load_state_dict(ckpt["state_dict"])
        start_epoch  = int(ckpt.get("epoch", 0)) + 1
        best_val_mae = float(np.mean(ckpt.get("val_mae", [float("inf")])))
    else:
        raw_model = ED2EModel(cfg).to(device)

    # Wrap with DDP after moving to device
    if is_ddp:
        model = DDP(raw_model, device_ids=[local_rank],
                    find_unused_parameters=False,
                    gradient_as_bucket_view=True)
    else:
        model = raw_model

    num_params = sum(p.numel() for p in raw_model.parameters())
    if is_main:
        print(f"Model parameters: {num_params:,}")
        print(f"Grad checkpointing: {cfg.bblock.use_gradient_checkpointing}")
        print(f"Grad accumulation steps: {args.grad_accum}")
        if is_ddp:
            print(f"DDP world size: {world_size}")

    optimizer = torch.optim.AdamW(
        model.parameters(), lr=args.lr, weight_decay=args.weight_decay
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs
    )

    # ── W&B (rank 0 only) ────────────────────────────────────────────────────
    use_wandb = args.wandb and is_main
    if use_wandb and not _WANDB_AVAILABLE:
        print("Warning: --wandb requested but `wandb` not installed. Continuing without W&B.")
        use_wandb = False

    if use_wandb:
        run_name = args.wandb_run_name or os.path.basename(os.path.abspath(args.out_dir))
        _wandb.init(
            project=args.wandb_project,
            entity=args.wandb_entity,
            name=run_name,
            tags=args.wandb_tags,
            config={
                "num_bblocks":         args.num_bblocks,
                "num_heads":           args.num_heads,
                "head_hidden":         args.head_hidden,
                "dropout":             args.dropout,
                "batch_size":          args.batch_size,
                "grad_accum":          args.grad_accum,
                "effective_batch":     args.batch_size * world_size * args.grad_accum,
                "epochs":              args.epochs,
                "lr":                  args.lr,
                "weight_decay":        args.weight_decay,
                "amp":                 use_amp,
                "grad_checkpointing":  cfg.bblock.use_gradient_checkpointing,
                "world_size":          world_size,
                "device":              str(device),
                "num_params":          num_params,
                "train_size":          len(train_ds),
                "val_size":            len(val_ds) if val_ds else 0,
                "resume":              args.resume,
            },
            resume="allow" if args.resume else False,
        )
        _wandb.watch(model, log="gradients", log_freq=200)

    # ── Log file (rank 0 only) ────────────────────────────────────────────────
    log_f = open(os.path.join(args.out_dir, "train_log.jsonl"), "a") if is_main else None

    # ── Training loop ─────────────────────────────────────────────────────────
    T            = cfg.num_targets
    global_step  = 0   # counts optimizer steps (not micro-steps)

    _INPUT_FIELDS = [
        "node_scalar_raw", "node_vector_raw", "node_tangent_basis",
        "membership_weight", "local_edge_attr",
        "chart_es_geom_static", "intra_geom_static",
        "inter_level_edge_attr", "inter_level_weights",
    ]

    for epoch in range(start_epoch, args.epochs):
        if is_ddp:
            train_sampler.set_epoch(epoch)   # re-shuffle per epoch for DDP

        model.train()
        optimizer.zero_grad()

        epoch_loss  = 0.0
        opt_steps   = 0
        t0          = time.perf_counter()

        for batch_idx, (batch, targets) in enumerate(train_loader):
            # ── H2D transfer (non-blocking; overlaps with prev GPU work) ──────
            batch   = batch.to(device, non_blocking=True)
            targets = targets.to(device, non_blocking=True)

            # ── Bad-input guard ───────────────────────────────────────────────
            bad_input = None
            for _fname in _INPUT_FIELDS:
                _t = getattr(batch, _fname, None)
                if _t is not None and isinstance(_t, torch.Tensor) and _t.is_floating_point():
                    if _t.isnan().any() or _t.isinf().any():
                        bad_input = _fname
                        break
            if bad_input is not None:
                if is_main:
                    print(f"  [WARN] NaN/Inf in '{bad_input}' at step={batch_idx+1} "
                          f"mol_ids={batch.mol_ids}; skipping batch.")
                # Keep optimizer state consistent: clear any partial gradients
                optimizer.zero_grad()
                continue

            # ── Determine whether this micro-step should sync gradients ───────
            n_batches     = len(train_loader)
            is_sync_step  = (
                (batch_idx + 1) % args.grad_accum == 0
                or (batch_idx + 1) == n_batches
            )
            # With DDP, skip allreduce on non-sync micro-steps to save bandwidth
            ddp_ctx = model.no_sync() if (is_ddp and not is_sync_step) else nullcontext()

            # ── Forward + backward ────────────────────────────────────────────
            with ddp_ctx:
                with amp_ctx:
                    out  = model(batch)
                    pred = out["energy_pred"]
                    # Scale loss by 1/grad_accum so gradient magnitude is
                    # independent of accumulation depth.
                    loss = sum(
                        F.huber_loss(pred[:, t], targets[:, t], delta=1.0)
                        for t in range(T)
                    ) / T / args.grad_accum

                if torch.isnan(loss) or torch.isinf(loss):
                    if is_main:
                        print(f"  [WARN] NaN/Inf loss at epoch={epoch} "
                              f"step={batch_idx+1} mol_ids={batch.mol_ids[:4]}; skipping.")
                    optimizer.zero_grad()
                    continue

                loss.backward()

            # ── Optimizer step (only at sync points) ──────────────────────────
            if is_sync_step:
                has_bad_grad = any(
                    p.grad is not None
                    and (p.grad.isnan().any() or p.grad.isinf().any())
                    for p in model.parameters()
                )
                if has_bad_grad:
                    if is_main:
                        print(f"  [WARN] NaN/Inf grad at epoch={epoch} "
                              f"step={batch_idx+1} mol_ids={batch.mol_ids[:4]}; "
                              f"skipping optimizer step.")
                    optimizer.zero_grad()
                    continue

                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                optimizer.step()
                optimizer.zero_grad()

                epoch_loss  += loss.detach().item() * args.grad_accum   # un-scale for logging
                opt_steps   += 1
                global_step += 1

                if is_main and args.log_every > 0 and global_step % args.log_every == 0:
                    avg_so_far = epoch_loss / opt_steps
                    lr_now     = scheduler.get_last_lr()[0]
                    print(f"  [ep {epoch:3d} opt_step {global_step:5d}]  "
                          f"loss={avg_so_far:.4f}  lr={lr_now:.2e}")
                    if use_wandb:
                        _wandb.log({
                            "train/loss_step": loss.item() * args.grad_accum,
                            "train/loss_avg":  avg_so_far,
                            "train/lr":        lr_now,
                        }, step=global_step)

        scheduler.step()
        avg_train_loss = epoch_loss / max(opt_steps, 1)
        elapsed = time.perf_counter() - t0

        # ── Validation (rank 0 only) ──────────────────────────────────────────
        if is_main:
            if val_loader is not None:
                val_metrics = _evaluate(
                    raw_model, val_loader, device, norm_stats,
                    T, cfg.target_names, amp_ctx,
                )
                val_mae = val_metrics["mae_mean"]
            else:
                val_metrics = {"loss": float("nan"), "mae_mean": float("nan")}
                for n in cfg.target_names:
                    val_metrics[f"mae_{n}"] = float("nan")
                val_mae = float("nan")

            log_entry = {
                "epoch":        epoch,
                "train_loss":   avg_train_loss,
                "val_loss":     val_metrics["loss"],
                "val_mae_mean": val_mae,
                **{k: v for k, v in val_metrics.items() if k.startswith("mae_")},
                "elapsed_s":    elapsed,
            }
            log_f.write(json.dumps(log_entry) + "\n")
            log_f.flush()

            if use_wandb:
                wandb_metrics: Dict[str, float] = {
                    "epoch":            epoch,
                    "train/loss_epoch": avg_train_loss,
                    "train/lr_epoch":   scheduler.get_last_lr()[0],
                    "perf/epoch_s":     elapsed,
                }
                if val_loader is not None:
                    wandb_metrics["val/loss"]     = val_metrics["loss"]
                    wandb_metrics["val/mae_mean"] = val_mae
                    for name in cfg.target_names:
                        wandb_metrics[f"val/mae_{name}"] = val_metrics[f"mae_{name}"]
                _wandb.log(wandb_metrics, step=global_step)

            # ── Console summary ───────────────────────────────────────────────
            val_str = (
                f"val_loss={val_metrics['loss']:.4f}  val_MAE={val_mae:.4f} Ha"
                if val_loader is not None else "val=N/A"
            )
            print(
                f"Epoch {epoch:3d}/{args.epochs-1}  "
                f"train_loss={avg_train_loss:.4f}  "
                f"{val_str}  ({elapsed:.0f}s)"
            )
            if val_loader is not None:
                for name in cfg.target_names:
                    print(f"    {name:>20}: {val_metrics[f'mae_{name}']:.6f} Ha")

            # ── Checkpoints ───────────────────────────────────────────────────
            val_mae_arr = np.array(
                [val_metrics.get(f"mae_{n}", float("nan")) for n in cfg.target_names]
            )
            last_ckpt = os.path.join(args.out_dir, "last.pt")
            _save_checkpoint(last_ckpt, raw_model, norm_stats, epoch, val_mae_arr)

            if val_loader is not None and val_mae < best_val_mae:
                best_val_mae = val_mae
                best_ckpt    = os.path.join(args.out_dir, "best.pt")
                _save_checkpoint(best_ckpt, raw_model, norm_stats, epoch, val_mae_arr)
                print(f"  → new best checkpoint (val_MAE={val_mae:.4f})")
                if use_wandb:
                    _wandb.summary["best_val_mae"]   = val_mae
                    _wandb.summary["best_val_epoch"] = epoch
                    for name in cfg.target_names:
                        _wandb.summary[f"best_mae_{name}"] = val_metrics[f"mae_{name}"]

    # ── Clean-up ─────────────────────────────────────────────────────────────
    if log_f is not None:
        log_f.close()
    if use_wandb:
        _wandb.finish()
    if is_ddp:
        dist.destroy_process_group()

    if is_main:
        print(f"\nTraining complete. Best val_MAE={best_val_mae:.4f} Hartree")
        print(f"Checkpoints: {args.out_dir}")


if __name__ == "__main__":
    main()
