#!/usr/bin/env python3
"""
ED2E training script.

Data layout expected:
    <data-dir>/
        packed_stage3/          ← Stage3PackedDataset (sharded)
        split.json              ← {"train": [...], "val": [...], "test": [...]}
        energy_stats.json       ← {"mean": (6,), "std": (6,), "target_names": [...]}

Generated by scripts/preprocess_edbench.py.

Usage
-----
::

    python scripts/train.py \
        --data-dir  data/ed_energy_5w \
        --csv-path  data/ed_energy_5w/raw/ed_energy_5w.csv \
        --out-dir   runs/stage6_k3 \
        --num-bblocks 3 --batch-size 8 --epochs 50 --device cuda

Resume from checkpoint:
    python scripts/train.py ... --resume runs/stage6_k3/best.pt
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(_HERE))

from ed2e.data.energy_stats import load_energy_labels, load_energy_stats, denormalise
from ed2e.data.stage3_local import Stage3Sample, collate_stage3_samples
from ed2e.data.stage3_packed import Stage3PackedDataset
from ed2e.model.bblock import BBlockConfig
from ed2e.model.ed2e import ED2EConfig, ED2EModel, TARGET_NAMES
from ed2e.model.readout import ReadoutConfig


# ══════════════════════════════════════════════════════════════════════════════
# Dataset wrapper
# ══════════════════════════════════════════════════════════════════════════════

class LabeledPackedDataset(Dataset):
    """
    Wraps Stage3PackedDataset, attaching energy labels from CSV.
    Returns (Stage3Sample, label_normalised) pairs.
    """

    def __init__(
        self,
        packed_dir: str,
        csv_path: str,
        mol_ids: List[str],
        norm_stats: Dict[str, np.ndarray],
    ) -> None:
        self.label_map = load_energy_labels(csv_path)
        mean = norm_stats["mean"]   # (6,)
        std  = norm_stats["std"]    # (6,)

        # Only keep mol_ids that have labels
        self.mol_ids = [m for m in mol_ids if m in self.label_map]
        if not self.mol_ids:
            raise ValueError("No labelled molecules found. Check csv_path and mol_ids.")

        self.base    = Stage3PackedDataset(packed_dir, mol_ids=self.mol_ids)
        self._mean   = mean
        self._std    = std

    def __len__(self) -> int:
        return len(self.mol_ids)

    def __getitem__(self, idx: int) -> Tuple[Stage3Sample, np.ndarray]:
        sample = self.base[idx]
        mol_id = self.mol_ids[idx]
        raw    = self.label_map[mol_id]           # (6,) float32
        normed = (raw - self._mean) / self._std   # (6,) float32
        return sample, normed


def labeled_collate(batch, device=None):
    samples, labels = zip(*batch)
    tb = collate_stage3_samples(list(samples), device=device)
    targets = torch.tensor(np.stack(labels), dtype=torch.float32)
    if device is not None:
        targets = targets.to(device)
    return tb, targets


# ══════════════════════════════════════════════════════════════════════════════
# Training helpers
# ══════════════════════════════════════════════════════════════════════════════

def _make_collate(device):
    def _collate(batch):
        return labeled_collate(batch, device=device)
    return _collate


@torch.no_grad()
def _evaluate(
    model: ED2EModel,
    loader: DataLoader,
    device: torch.device,
    norm_stats: Dict[str, np.ndarray],
) -> Dict[str, float]:
    """Compute per-target MAE in Hartree (denormalised)."""
    model.eval()
    mean_t = torch.tensor(norm_stats["mean"], dtype=torch.float32, device=device)
    std_t  = torch.tensor(norm_stats["std"],  dtype=torch.float32, device=device)

    abs_errors: List[torch.Tensor] = []
    total_loss = 0.0
    n_batches  = 0

    for batch, targets in loader:
        targets = targets.to(device)
        out     = model(batch)
        pred    = out["energy_pred"]          # (B, T) normalised

        loss = sum(
            F.huber_loss(pred[:, t], targets[:, t], delta=1.0)
            for t in range(model.cfg.num_targets)
        ) / model.cfg.num_targets
        total_loss += float(loss)
        n_batches  += 1

        # Denormalise for MAE
        pred_raw    = pred * std_t + mean_t    # (B, T)
        targets_raw = targets * std_t + mean_t
        abs_errors.append((pred_raw - targets_raw).abs().cpu())

    mae_per_target = torch.cat(abs_errors, dim=0).mean(dim=0)   # (T,)
    result = {"loss": total_loss / max(n_batches, 1)}
    for i, name in enumerate(model.cfg.target_names):
        result[f"mae_{name}"] = float(mae_per_target[i])
    result["mae_mean"] = float(mae_per_target.mean())
    return result


def _save_checkpoint(
    path: str,
    model: ED2EModel,
    norm_stats: Dict[str, np.ndarray],
    epoch: int,
    val_mae: np.ndarray,
) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    torch.save(
        {
            "config":     model.cfg,
            "state_dict": model.state_dict(),
            "norm_mean":  norm_stats["mean"],
            "norm_std":   norm_stats["std"],
            "epoch":      epoch,
            "val_mae":    val_mae,
        },
        path,
    )


# ══════════════════════════════════════════════════════════════════════════════
# CLI
# ══════════════════════════════════════════════════════════════════════════════

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Train ED2EModel on EDBench energy prediction.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--data-dir",    required=True,
                   help="Root dir containing packed_stage3/, split.json, energy_stats.json")
    p.add_argument("--csv-path",    required=True,
                   help="Path to ed_energy_5w.csv (for energy labels)")
    p.add_argument("--out-dir",     required=True,
                   help="Checkpoint / log output directory")

    # model
    p.add_argument("--num-bblocks",  type=int,   default=3)
    p.add_argument("--num-heads",    type=int,   default=4)
    p.add_argument("--head-hidden",  type=int,   default=128)
    p.add_argument("--dropout",      type=float, default=0.1)

    # training
    p.add_argument("--batch-size",   type=int,   default=8)
    p.add_argument("--epochs",       type=int,   default=100)
    p.add_argument("--lr",           type=float, default=1e-3)
    p.add_argument("--weight-decay", type=float, default=1e-4)
    p.add_argument("--num-workers",  type=int,   default=0,
                   help="DataLoader workers (0 = main process)")

    # misc
    p.add_argument("--device",   default="cpu")
    p.add_argument("--resume",   default=None,
                   help="Path to checkpoint to resume from")
    p.add_argument("--log-every", type=int, default=50,
                   help="Log training loss every N steps")
    return p.parse_args()


def main() -> None:
    args = _parse_args()
    device = torch.device(args.device)
    os.makedirs(args.out_dir, exist_ok=True)

    packed_dir  = os.path.join(args.data_dir, "packed_stage3")
    split_path  = os.path.join(args.data_dir, "split.json")
    stats_path  = os.path.join(args.data_dir, "energy_stats.json")

    # ── Split & stats ─────────────────────────────────────────────────────────
    print(f"Loading split from {split_path} …")
    with open(split_path) as f:
        splits = json.load(f)
    print(f"  train={len(splits['train'])}  val={len(splits['val'])}  "
          f"test={len(splits.get('test', []))}")

    print(f"Loading energy stats from {stats_path} …")
    norm_stats = load_energy_stats(stats_path)

    # ── Datasets & loaders ───────────────────────────────────────────────────
    collate_fn = _make_collate(device)

    train_ds = LabeledPackedDataset(packed_dir, args.csv_path,
                                    splits["train"], norm_stats)
    val_ds   = LabeledPackedDataset(packed_dir, args.csv_path,
                                    splits["val"],   norm_stats)
    print(f"  train={len(train_ds)}  val={len(val_ds)} (labelled)")

    train_loader = DataLoader(
        train_ds, batch_size=args.batch_size, shuffle=True,
        collate_fn=collate_fn, num_workers=args.num_workers,
        pin_memory=False,   # tensors already on device via collate_fn
    )
    val_loader = DataLoader(
        val_ds, batch_size=args.batch_size, shuffle=False,
        collate_fn=collate_fn, num_workers=args.num_workers,
    )

    # ── Model ─────────────────────────────────────────────────────────────────
    cfg = ED2EConfig(
        bblock=BBlockConfig(num_bblocks=args.num_bblocks),
        readout=ReadoutConfig(num_heads=args.num_heads),
        energy_head_hidden=args.head_hidden,
        energy_dropout=args.dropout,
    )

    start_epoch = 0
    best_val_mae = float("inf")

    if args.resume:
        print(f"Resuming from {args.resume} …")
        ckpt = torch.load(args.resume, map_location="cpu")
        model = ED2EModel(ckpt["config"]).to(device)
        model.load_state_dict(ckpt["state_dict"])
        start_epoch = int(ckpt.get("epoch", 0)) + 1
        best_val_mae = float(np.mean(ckpt.get("val_mae", [float("inf")])))
    else:
        model = ED2EModel(cfg).to(device)

    num_params = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {num_params:,}")

    optimizer = torch.optim.AdamW(
        model.parameters(), lr=args.lr, weight_decay=args.weight_decay
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs
    )

    # ── Log file ──────────────────────────────────────────────────────────────
    log_path = os.path.join(args.out_dir, "train_log.jsonl")
    log_f = open(log_path, "a")

    # ── Training loop ─────────────────────────────────────────────────────────
    T = cfg.num_targets
    for epoch in range(start_epoch, args.epochs):
        model.train()
        epoch_loss = 0.0
        step = 0
        t0   = time.perf_counter()

        for batch_idx, (batch, targets) in enumerate(train_loader):
            targets = targets.to(device)
            optimizer.zero_grad()

            out  = model(batch)
            pred = out["energy_pred"]   # (B, T)

            loss = sum(
                F.huber_loss(pred[:, t], targets[:, t], delta=1.0)
                for t in range(T)
            ) / T

            loss.backward()
            optimizer.step()

            epoch_loss += float(loss)
            step        += 1

            if args.log_every > 0 and (batch_idx + 1) % args.log_every == 0:
                print(f"  [ep {epoch:3d} step {batch_idx+1:4d}]  "
                      f"loss={epoch_loss/step:.4f}  "
                      f"lr={scheduler.get_last_lr()[0]:.2e}")

        scheduler.step()
        avg_train_loss = epoch_loss / max(step, 1)
        elapsed = time.perf_counter() - t0

        # ── Validation ────────────────────────────────────────────────────────
        val_metrics = _evaluate(model, val_loader, device, norm_stats)
        val_mae     = val_metrics["mae_mean"]

        log_entry = {
            "epoch":       epoch,
            "train_loss":  avg_train_loss,
            "val_loss":    val_metrics["loss"],
            "val_mae_mean": val_mae,
            **{k: v for k, v in val_metrics.items() if k.startswith("mae_")},
            "elapsed_s":   elapsed,
        }
        log_f.write(json.dumps(log_entry) + "\n")
        log_f.flush()

        # ── Console summary ───────────────────────────────────────────────────
        print(
            f"Epoch {epoch:3d}/{args.epochs-1}  "
            f"train_loss={avg_train_loss:.4f}  "
            f"val_loss={val_metrics['loss']:.4f}  "
            f"val_MAE={val_mae:.4f} Hartree  "
            f"({elapsed:.0f}s)"
        )
        for name in cfg.target_names:
            print(f"    {name:>20}: {val_metrics[f'mae_{name}']:.6f} Ha")

        # ── Checkpoint ────────────────────────────────────────────────────────
        val_mae_arr = np.array([val_metrics[f"mae_{n}"] for n in cfg.target_names])
        last_ckpt   = os.path.join(args.out_dir, "last.pt")
        _save_checkpoint(last_ckpt, model, norm_stats, epoch, val_mae_arr)

        if val_mae < best_val_mae:
            best_val_mae = val_mae
            best_ckpt    = os.path.join(args.out_dir, "best.pt")
            _save_checkpoint(best_ckpt, model, norm_stats, epoch, val_mae_arr)
            print(f"  → new best checkpoint (val_MAE={val_mae:.4f})")

    log_f.close()
    print(f"\nTraining complete. Best val_MAE={best_val_mae:.4f} Hartree")
    print(f"Checkpoints: {args.out_dir}")


if __name__ == "__main__":
    main()
